version: '3.7'
services:
  grafana:
    build: ./grafana
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
    - "3000:3000"
    depends_on:
      - prometheus
  prometheus:
    build: ./prometheus
    container_name: prometheus
    ports:
    - "9090:9090"
    depends_on:
      - node_exporter
      - java_app
    extra_hosts:
      - "host.docker.internal:host-gateway"
  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node_exporter
    ports:
    - "9100:9100"
    command:
      - '--path.rootfs=/host --cap-add=SYS_TIME'
    network_mode: host
  java_app:
    build: ./java_app
    container_name: java_app
    ports:
    - "8080:8080"
  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  promtail:
    image: grafana/promtail:2.8.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml