version: '3.7'
services:
  grafana:
    build: ./grafana
    ports:
    - "3000:3000"
    depends_on:
      - prometheus
  prometheus:
    build: ./prometheus
    ports:
    - "9090:9090"
    depends_on:
      - node_exporter
  node_exporter:
    image: quay.io/prometheus/node-exporter
    ports:
    - "9100:9100"