version: '3.7'
services:
  grafana:
    build: ./grafana
    ports:
    - "3000:3000"
    depends_on:
      - prometheus
  prometheus:
    build: ./prometheus
    ports:
    - "9090:9090"
    depends_on:
      - node_exporter
      - java_app
    extra_hosts:
      - "host.docker.internal:host-gateway"
  node_exporter:
    image: quay.io/prometheus/node-exporter
    ports:
    - "9100:9100"
    command:
      - '--path.rootfs=/host --cap-add=SYS_TIME'
    network_mode: host
  java_app:
    build: ./java_app
    ports:
    - "8080:8080"
